version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Packaging the HTML application...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/*
  discard-paths: no